config/routes.rb
StartupWeekend::Application.routes.draw do

   root 'home#index'

  resources :website do
    collection do
      get "theme"
    end
  end

  resources :customers
  resources :campaigns
  resources :reviews
  resources :social_media
  resources :feedback

  devise_for :admins, :sign_out_via => [ :get ], path: "admin" do
    get "/admin", :to => "devise/sessions#new"
  end
  namespace :admin do
    resources :dashboard, only: [:index]
    get "imports" => "dashboard#imports", as: :imports
    post "do_import" => "dashboard#do_import", as: :do_import
    resources :customers
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # get full name
  def full_name
    [first_name, last_name].join(" ").try(:strip) rescue nil
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :customer
  belongs_to :store
  # has_one :store, through :question
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :answers
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :stores
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :store
  has_many :answers
end

app/models/store.rb
class Store < ActiveRecord::Base
  
  # Friendly ID
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :location
  has_many :questions
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	def index
		@customers = Customer.all
		@areas = Location.all		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_dashboard_index_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
     new_admin_session_path
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
		@areas = Location.all		
	end
	def new
		@customer = Customer.new
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
  end

  def theme
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/admin/customers/index.html.haml
.content
  .span24
    = select_tag "location", options_from_collection_for_select(@areas, "id", "area")
    %input#dp1.span2{type: "text", value: "02-16-2012"}
  .span24
    - if @customers && @customers.size > 0
      .span24
        %table.table.table-hover
          %tr
            %th S.No
            %th Name
            %th Email
            %th Phone Number
            %th Visits
            %th Contact
          - @customers.each_with_index do |cus, index|
            %tr
              %td= index
              %td= cus.name
              %td= cus.email
              %td= cus.contact_number
              %td= index
              %td Email Phone
    - else
      .span24
        %table.table.table-hover
          %tr
            %td No records Found  

app/views/customers/_form.html.haml
.row-fluid
  .span20.pull-right
    .row-fluid
      .span24
        = f.label :name
        = f.text_field :name
      .span24(style="margin-left:0px;")
        = f.label :email
        = f.text_field :contact_number
      .span24(style="margin-left:0px;")
        = f.label :contact_number
        = f.text_field :contact_number
      .span24(style="margin-left:0px;")
        = f.label :dob
        = f.text_field :contact_number
      .span24(style="margin-left:0px;")
        = f.label :dob
        = f.text_field :contact_number

app/views/customers/index.html.haml
.bread-crumb
  = link_to "Home", "/"
  >
  = link_to "Customers", customers_path
.main-header
  .span4
    %h3 Customers
  .span20
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")
  .span24.customer-list(style="margin:0;padding:0;margin-top:10px;background:white;padding-top:20px;padding-bottom:50px;min-height:600px")
    .span18.filters
      %ul
        %li.span4(style="padding:10px;background:#CCC;color:white;margin-left:10px;")
          %div.dropdown
            %a(href="#" data-toggle="dropdown" style="color:black")
              By Location
              %i.fa.fa-caret-down
            %ul(class="dropdown-menu" role="menu" aria-labelledby="dLabel" style="border-radius:0;margin-top:10px;margin-left:-10px;")
              %li.span24
                %a(href="#" style="padding:10px;background:white;color:black;border-bottom:1px solid #CCC") 
                  Koramangala
              - ["Indiranagar", "Whitefield", "Electronic City", "BTM", "HSR Layout"].each do |content|
                %li.span24(style="padding:0;margin:0;")
                  %a(href="#" style="padding:10px;background:white;color:black;border-bottom:1px solid #CCC")
                    = content
                  

        %li.span3(style="padding:10px;padding-top:5px;padding-bottom:5px;;background:#CCC;color:white;margin-left:10px;")
          %input(type="text" style="border:1px solid #CCC;color:black;background:#CCC;outline:none;box-shadow:none;padding:0;margin:0" placeholder="Start Date" class="datepicker span20")
        %li.span3(style="padding:10px;padding-top:5px;padding-bottom:5px;;background:#CCC;color:white;margin-left:10px;")
          %input(type="text" style="border:1px solid #CCC;color:black;background:#CCC;outline:none;box-shadow:none;padding:0;margin:0" placeholder="End Date" class="datepicker span20")
        %li
          %input(type="search" placeholder="Search Email / Contact" style="padding-top:9px;padding-bottom:9px;margin-left:10px;border-radius:0;box-shadow:none;border-color:#CCC;outline:none;")
    = link_to "Add Customers", "#", class: "span3", style: "padding: 8px 10px;background:#BE2121;margin-right: 35px;float:right;color:white;text-shadow:1px 0 1px black;font-size:15px;text-align:center;"
    .span23
      %table(class="table table-striped")
        %tr
          %th S.No
          %th Name
          %th Email
          %th Contact No
          %th Vists
          %th Contact
        -  [@customers, @customers, @customers, @customers].flatten.each_with_index do |cus, index|
          %tr
            %td= index + 1
            %td= cus.name
            %td= cus.email
            %td= cus.contact_number
            %td= index
            %td 
              = link_to "Email", "#", style: "color: black"
              |
              = link_to "Phone", "#", style: "color: black"

app/views/customers/new.html.haml
- if @customer && @customer.errors
  .error_area
    = @customer.errors.full_messages.join(",")
.content
  .span24(style="margin-bottom:50px;")
    = form_for :customer, :html => { :class => "validate" } ,  url: customers_path, html: {multipart: true, class: "no-radius"} do |f|
      = render partial: "form", locals: {f: f}
      %br
      = f.submit "Create", class: "btn btn-small btn-success cap pull-right span3"
      .clear
      %hr