config/routes.rb
StartupWeekend::Application.routes.draw do

   root 'home#index'

  resources :website do
    collection do
      get "theme"
    end
  end

  resources :customers
  resources :campaigns
  resources :reviews
  resources :social_media
  resources :feedback

  devise_for :admins, :sign_out_via => [ :get ], path: "admin" do
    get "/admin", :to => "devise/sessions#new"
  end
  namespace :admin do
    resources :dashboard, only: [:index]
    get "imports" => "dashboard#imports", as: :imports
    post "do_import" => "dashboard#do_import", as: :do_import
    resources :customers
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # get full name
  def full_name
    [first_name, last_name].join(" ").try(:strip) rescue nil
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :customer
  belongs_to :store
  # has_one :store, through :question
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :answers
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :stores
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :store
  has_many :answers
end

app/models/store.rb
class Store < ActiveRecord::Base
  
  # Friendly ID
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :location
  has_many :questions
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
		@areas = Location.all		
	end
	def new
		@customer = Customer.new
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
  end

  def theme
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/campaigns/index.html.haml
.bread-crumb
  = link_to "Home", root_path
  >
  = link_to "Campaigns", campaigns_path
.main-header
  .span4
    %h3 Campaigns
  .span20
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")

app/views/feedback/index.html.haml
.bread-crumb
  = link_to "Home", root_path
  >
  = link_to "Feedback", feedback_index_path
.main-header
  .span6
    %h3 Feedback
  .span18
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")

app/views/home/_graph.html.haml
%script{src: "https://www.google.com/jsapi", type: "text/javascript"}
.span20.offset2.graph-table(style= "margin-bottom:20px")
  .span5.visits
    %i.fa.fa-list-ul(style="margin-left:5px;padding-top:10px;font-size:18px")
    %span(style="font-size:16px;margin-left:5px") Total Visits
  .span5.visits
    %span(style="font-size:14px;margin-left:5px") Select month
    %i.fa.fa-caret-down(style="margin-left:35px;padding-top:10px;font-size:18px")
  .span24#chart_div(style="height:350px;border-top:1px solid #d1d1d1;margin:0px")
  .span24.counts
    .span6.number
      %h3 1234
      %h5.desc Total Views
    .span6.number
      %h3 676
      %h5.desc Last 24hours
    .span6.number
      %h3 78
      %h5.desc Unique Users
    .span6.number
      %h3 12347
      %h5.desc Total Orders


 

:javascript
  $(".datepicker").datepicker({format: "yyyy-mm-dd"});    
  google.load('visualization', '1.0', {'packages':['corechart']});   
  google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
       var data = google.visualization.arrayToDataTable([
          ['Month', 'Visit', 'orderd'],
          ['Jan',  1000,      400],
          ['Feb',  2000,      460],
          ['March', 500,       1000],
          ['Apr',  1010,      540]
        ]);
      var options = {'title':'How Many Vistors to your Restaurant', 'width':$("#chart_div").width(), 'height':350};

      var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }

app/views/home/_second_graph.html.haml
%script{src: "https://www.google.com/jsapi", type: "text/javascript"}
.span10.graph-table.offset2
  .span10.visits
    %i.fa.fa-list-ul(style="margin-left:5px;padding-top:10px;font-size:18px")
    %span(style="font-size:16px;margin-left:5px") Total Visits
  .visits
    %span(style="font-size:14px;margin-left:15px") Select month
    %i.fa.fa-caret-down(style="margin-left:35px;padding-top:10px;font-size:18px")
  .span24#second_chart(style="height:350px;border-top:1px solid #d1d1d1;margin:0px")
  .span24.counts
    .span12.number
      %h3 1234
      %h5.desc Total Orders
    .span12.number
      %h3 1234
      %h5.desc Orders Today
    
= render partial: "home/third"

:javascript
  google.load('visualization', '1.0', {'packages':['corechart']});   
  google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
       var data = google.visualization.arrayToDataTable([
          ['18/11', 1000 ],
          ['19/11',  1000],
          ['20/11',  2000],
          ['21/11', 500],
          ['22/11',  1010],
          ['23/11', 500],
          ['24/11',  1010],
        ]);
      var options = {'title':'Orders 18/11-24/11',
                     'width':$("#second_chart").width(),
                     'height':350};

      var chart = new google.visualization.AreaChart(document.getElementById('second_chart'));
      chart.draw(data, options);
    }

 

app/views/home/_third.html.haml
.span10.graph-table
  .span10.visits
    %i.fa.fa-list-ul(style="margin-left:5px;padding-top:10px;font-size:18px")
    %span(style="font-size:16px;margin-left:5px") Total Visits
  .visits
    %span(style="font-size:14px;margin-left:15px") Select stores
    %i.fa.fa-caret-down(style="margin-left:35px;padding-top:10px;font-size:18px")
  .span24#third_chart(style="height:350px;border-top:1px solid #d1d1d1;margin:0px")
  .span24.counts
    .span8.number
      %h3 50%
      %h5.desc Facebook
    .span8.number
      %h3 30%
      %h5.desc Twitter
    .span8.number
      %h3 20%
      %h5.desc Foursquare

:javascript
  google.load('visualization', '1.0', {'packages':['corechart']});   
  google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
       var data = google.visualization.arrayToDataTable([
          ['Date', 'Facebook', "Twitter", "Foursquare"],
          ['22/11', 1000, 800, 400  ],
          ['23/11', 950, 700, 450],
          ['24/11', 1100, 790, 425]
        ]);
      var options = {'title':'Insights',
                     'width':$("#third_chart").width(),
                     'height':350};

      var chart = new google.visualization.BarChart(document.getElementById('third_chart'));
      chart.draw(data, options);
    }

app/views/home/index.html.haml
.bread-crumb
  = link_to "Home", "/"
  >
  = link_to "Dashboard", "/"
.main-header
  .span4
    %h3 Dashboard  
  .span20
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")
  .span24.home-stats(style="margin-bottom: 20px;")
    .stat.span5.offset2
      .content
        %i.fa.fa-group.pull-left(style="background: #519816")
        .stat-content.span10.pull-right
          %h5 Visitors
          .count
            +1000
        %div(style="clear:both")
      .view-more.span22
        = link_to "VIEW MORE"
      %div(style="clear:both")
    .stat.span5
      .content
        %i.fa.fa-bullhorn.pull-left
        .stat-content.span15.pull-right
          %h5 Reach
          .count
            79%
        %div(style="clear:both")
      .view-more.span22
        = link_to "VIEW MORE"
      %div(style="clear:both")
    .stat.span5
      .content
        %i.fa.fa-clock-o.pull-left(style="background: #E5CE24")
        .stat-content.span10.pull-right
          %h5 Insights
          .count
            +1000
        %div(style="clear:both")
      .view-more.span22
        = link_to "VIEW MORE"
      %div(style="clear:both")
    .stat.span5
      .content
        %i.fa.fa-thumbs-up.pull-left(style="background: #A529A5")
        .stat-content.span10.pull-right
          %h5 Feedbacks
          .count
            +1000
        %div(style="clear:both")
      .view-more.span22
        = link_to "VIEW MORE"
      %div(style="clear:both")
  .home-graphs(style="margin:0px;")
    = render partial: "home/graph"
  .home-graphs(style="margin:0px;")
    = render partial: "home/second_graph"

app/views/reviews/.#index.html.haml
jaikeerthi@Jais-MacBook-Air.local.184

app/views/reviews/index.html.haml
.bread-crumb
  = link_to "Home", "/"
  >
  = link_to "Review", "/"
.main-header
  .span4
    %h3 Review  
  .span20
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")
.review(style="background-color:#fff;")
  .container
    .span24(style= "margin-bottom:20px;margin-top:20px")
      .span2(style="border:1px solid #000")
        %img.hover{src: "/assets/1.jpg"}
      .span22
        .link(style= "font-size:14px;font-weight:bold")
          = link_to "JAIKEERTHI"
        .from
          %span
            from
          %i= link_to "Zomato"
        .time(style= "color:#ccc")
          4 month ago 
        %p(style="margin-bottom:20px;font-size:15px")Tried this restaurant within a month or two of its opening. 
        %p(style="margin-bottom:20px;font-size:15px")
          The crowd in the restaurant made it look very promising. But the crowd was a bit too unruly.
        %p(style="font-size:15px") Ambiance - Nothing great to talk about
        %p(style="font-size:15px")
          Food - Back when i tried the biryani was just O.K. (but recent reviews from my foodie friends makes me want to give it another chance)
        %p(style="font-size:15px") Service - Nothing professional, but yeah fast enough
        %p(style="font-size:15px") Price - It justifies the quantity, decently priced
        %p(style="font-size:15px;margin-bottom:10px") Parking is ample
        .span6(style="margin:0px;")
          .span10(style= "border:1px solid #ccc;padding:5px;background-color:#eee")
            %span.fa.fa-mail-reply
            %span(style="margin-left:5px")= link_to "Reply"
          .span10(style= "border:1px solid #ccc;padding:5px;background-color:#eee;margin-left:5px")
            %span.fa.fa-share-square-o
            %span(style="margin-left:5px;")= link_to "Share"
        



    .span24(style= "margin-bottom:20px;margin-top:20px")
      .span2(style="border:1px solid #000")
        %img.hover{src: "/assets/1.jpg"}
      .span22
        .link(style= "font-size:14px;font-weight:bold")
          = link_to "GOWRISHANKAR"
        .from
          %span
            from
          %i= link_to "Zomato"
        .time(style= "color:#ccc")
          4 month ago 
        %p(style="margin-bottom:20px;font-size:15px")Tried this restaurant within a month or two of its opening. 
        %p(style="margin-bottom:20px;font-size:15px")
          The crowd in the restaurant made it look very promising. But the crowd was a bit too unruly.
        %p(style="font-size:15px") Ambiance - Nothing great to talk about
        %p(style="font-size:15px")
          Food - Back when i tried the biryani was just O.K. (but recent reviews from my foodie friends makes me want to give it another chance)
        %p(style="font-size:15px") Service - Nothing professional, but yeah fast enough
        %p(style="font-size:15px") Price - It justifies the quantity, decently priced
        %p(style="font-size:15px;margin-bottom:10px") Parking is ample
        .span6(style="margin:0px;")
          .span10(style= "border:1px solid #ccc;padding:5px;background-color:#eee")
            %span.fa.fa-mail-reply
            %span(style="margin-left:5px")= link_to "Reply"
          .span10(style= "border:1px solid #ccc;padding:5px;background-color:#eee;margin-left:5px")
            %span.fa.fa-share-square-o
            %span(style="margin-left:5px;")= link_to "Share"
        

app/views/website/index.html.haml
.bread-crumb
  = link_to "Home", root_path
  >
  = link_to "Website", website_index_path
.main-header
  .span4
    %h3 Website
  .span20
    .progress-bar.span10.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")
  .span24.website-start(style="margin:0;padding:0;margin-top:10px;background:white;padding-top:50px;padding-bottom:50px;min-height:600px")
    %h3(style="font-weight:300;text-align:center;color:#BE2121;text-transform:uppercase;letter-spacing:0px;font-size: 17px")
      You are 
      %strong(style="font-size: 20px;") 5 Steps
      away from establishing your online presence
    .brand.span24(style="text-align:center;margin:0;")
      %label.span24(style="text-align:center;font-size: 20px;")
        1. Choose your domain name
      .span10.offset8(style="margin-left: 33%;")
        %input.span19(type="text" name="" placeholder="Eg. empire" style="border-radius:0;box-shadow:none;outline:none;border:1px solid #ACAAAA")
        %label.span4.pull-right(style="color:green;font-weight:700;padding-top:3px;text-align:left;") Available
        %div(style="clear:both")
        %label.span19(style="text-align:center;margin-top:-10px;color:#949292;") http://empire.eatwithus.in
      .span20.offset3(style="text-align:left;")
        .row-fluid
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Koramangala
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Indiranagar
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Jayanagar
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Castle Street
        .row-fluid
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Church Street
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Central Street
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Frazer Town
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Kammanahalli
        .row-fluid
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Millers Road
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") 80-ft Road
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Noronha Road
          .span6(style="color:#BE2121;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px") Mysore
        .row-fluid
          .span6(style="color:#ACAAAA;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px;color:#ACAAAA") Orion Mall
            %span(style="font-size:10px;color:#ACAAAA;margin-top:-10px;")(Publish Outlet)
          .span6(style="color:#ACAAAA;font-weight:normal; line-height: 40px")
            %i.fa.fa-check-square-o(style="font-size:18px;padding-top:2px;")
            %a(style="font-size:14px;color:#ACAAAA") Madur
            %span(style="font-size:10px;color:#ACAAAA;margin-top:-10px;")(Publish Outlet)

      .span20.offset2(style="text-align:center;font-size:15px;margin-top:25px;color:#ACAAAA;font-weight:500")
        .span10.offset8
          %input.span1(type="checkbox" style="float: left;margin-top: 9px;text-align: right;")
          %div.span20(style="padding-top:4px;text-align: left;") I agree to RestoCRM Terms and Conditions
        %div(style="clear:both")
        %br
        = link_to "Create Online Store", theme_website_index_path, style: "background: #BE2121;color: white;padding: 8px 20px;text-shadow: 1px 0 1px black;"

app/views/website/theme.html.haml
.bread-crumb
  = link_to "Home", root_path
  >
  = link_to "Website", website_index_path
  >
  = link_to "Theme", theme_website_index_path
.main-header
  .span10
    %h3 Choose Theme
  .span14
    .progress-bar.span16.pull-right
    %div(style="clear:both")
    %span.pull-right(style="margin-right:10px;font-size: 11px;")
      72% of your profile completed
  %div(style="clear:both")
  .span24.website-start(style="margin:0;padding:0;margin-top:10px;padding-top:50px;padding-bottom:50px;min-height:600px")
    .counter.span20.offset3
      .span1(style="background:#ba121f;border-radius:25px;color:white;padding: 10px 25px 11px 18px;font-weight:bold;text-align:center")
        2
      .span6(style="margin:0;border-bottom: 1px solid #CCC;margin-top:-10px")
      .span1(style="background:white;border-radius:25px;color:#ba121f;padding: 10px 25px 11px 18px;font-weight:bold;text-align:center;margin:0;border:1px solid #CCC;")
        3
      .span6(style="margin:0;border-bottom: 1px solid #CCC;margin-top:-10px;")
      .span1(style="background:white;border-radius:25px;color:#ba121f;padding: 10px 25px 11px 18px;font-weight:bold;text-align:center;margin:0;border:1px solid #CCC;")
        4
      .span6(style="margin:0;border-bottom: 1px solid #CCC;margin-top:-10px;")
      .span1(style="background:white;border-radius:25px;color:#ba121f;padding: 10px 25px 11px 18px;font-weight:bold;text-align:center;margin:0;border:1px solid #CCC;")
        5
    .text.span22.offset2(style="text-align:center;")
      .span3 Choose Theme
      .span3.offset3 Configure
      .span4.offset3 Add Pages
      .span2.offset3 Launch

    .span24.theme(style= "margin-top:30px")
      .span6.offset2.thumb
        %img.img-thumbnail{src: "/assets/1.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/2.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/3.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
    .span24.theme(style= "margin-top:30px")
      .span6.offset2.thumb
        %img.img-thumbnail{src: "/assets/4.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/5.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/6.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
    .span24.theme(style= "margin-top:30px")
      .span6.offset2.thumb
        %img.img-thumbnail{src: "/assets/7.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/8.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
      .span6.offset1.thumb
        %img.img-thumbnail{src: "/assets/9.jpg"}
        %img.hover.hide{src: "/assets/hover.jpg"}
     
:javascript
  $( ".thumb" ).mouseenter(function() {
    $(this).find(".img-thumbnail").hide();
    $(this).find( ".hover" ).show();
  });
  $( ".thumb" ).mouseleave(function() {
    $(this).find(".img-thumbnail").show();
    $(this).find( ".hover" ).hide();
  });