config/routes.rb
StartupWeekend::Application.routes.draw do

   root 'home#index'

  resources :website do
    collection do
      get "theme"
    end
  end

  resources :customers
  resources :campaigns
  resources :reviews
  resources :social_media
  resources :feedback

  devise_for :admins, :sign_out_via => [ :get ], path: "admin" do
    get "/admin", :to => "devise/sessions#new"
  end
  namespace :admin do
    resources :dashboard, only: [:index]
    get "imports" => "dashboard#imports", as: :imports
    post "do_import" => "dashboard#do_import", as: :do_import
    resources :customers
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # get full name
  def full_name
    [first_name, last_name].join(" ").try(:strip) rescue nil
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :customer
  belongs_to :store
  # has_one :store, through :question
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :answers
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :stores
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :store
  has_many :answers
end

app/models/store.rb
class Store < ActiveRecord::Base
  
  # Friendly ID
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :location
  has_many :questions
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
  end

  def theme
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/views/layouts/_header.html.haml
.header.row-fluid
  .rest-logo.span5
    .span24.logo
      %a(href="#")
        Hotel Empire
      %i.fa.fa-arrow-circle-down
  .span19.menu
    %ul.span6
      %li.span12
        %a(href="#")
          %div(style="padding-top: 13px;")
            Dashboard
      %li.span12
        %div.dropdown(style="padding-top: 13px;")
          %a(href="#" data-toggle="dropdown")
            Settings
            %i.fa.fa-caret-down
          %ul(class="dropdown-menu" role="menu" aria-labelledby="dLabel")
            %li.span24
              %a(href="#")
                User Profile
                %i.fa.fa-user
            %li.span24
              %a(href="#")
                Change Password
                %i.fa.fa-key
            %li.span24
              %a(href="#")
                Notification
                %i.fa.fa-bell
            %li.span24
              %a(href="#")
                Plans & Pricing
                %i.fa.fa-tag
            %li.span24
              %a(href="#")
                Delete Account
                %i.fa.fa-trash-o
    %ul.right-menu.span8.pull-right
      %li.span4
        %a(href="#")
          %i.fa.fa-list-ul
      %li.span4
        %a(href="#")
          %i.fa.fa-bell
      %li.span4
        %a(href="#")
          %i.fa.fa-envelope
      %li.span12
        %div.dropdown
          %a(href="#" data-toggle="dropdown")
            %div.fa.fa-user
            Jaikeerthi
            %i.fa.fa-caret-down
          %ul(class="dropdown-menu" role="menu" aria-labelledby="dLabel" style="padding-left:24px;margin-left:auto;")
            %li.span24(style="padding-top:0;")
              %a(href="#")
                Logout

app/views/layouts/_side_pannel.html.haml
%ul
  %li(style="class: #{(controller_name == "home") ? "active" : "inactive" }")
    %a(href=root_path)
      .content
        %i.fa.fa-dashboard
        %span Dashboard
  %li(class="#{(controller_name == "website") ? "active" : "inactive" }")
    %a(href=website_index_path)
      .content
        %i.fa.fa-laptop
        %span Website
  %li(class="#{(controller_name == "customers") ? "active" : "inactive" }")
    %a(href=customers_path)
      .content
        %i.fa.fa-group
        %span Customers
  %li(class="#{(controller_name == "campaigns") ? "active" : "inactive" }")
    %a(href=campaigns_path)
      .content
        %i.fa.fa-envelope-o
        %span Campaign Manager
  %li(class="#{(controller_name == "reviews") ? "active" : "inactive" }")
    %a(href=reviews_path)
      .content
        %i.fa.fa-edit
        %span Reviews
  %li(class="#{(controller_name == "social_media") ? "active" : "inactive" }")
    %a(href=social_media_path)
      .content
        %i.fa.fa-rss
        %span Social Media
  %li(class="#{(controller_name == "feedback") ? "active" : "inactive" }")
    %a(href=feedback_index_path)
      .content
        %i.fa.fa-thumbs-up
        %span Feedback

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Restaurant CRM
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700'
    = csrf_meta_tags
  %body
    - if admin_signed_in?
      = link_to "Logout", destroy_admin_session_path, :method => "delete"
    - else
      = link_to "Sign in", new_admin_session_path 
    = render "layouts/header"
    .row-fluid
      .span5.side_panel
        = render "layouts/side_pannel"
      .span19#main.pull-right
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Restaurant CRM
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700'
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .row-fluid
      .span5.side_panel
        = render "layouts/side_pannel"
      .span19#main.pull-right(style="padding-bottom: 20px;margin-top: 52px;")
        = yield